package com.journey.common.error;

import org.springframework.http.HttpStatus;

/**
 * Every error the API can answer with, in one catalog — the error equivalent of the status and role enums.
 *
 * <p>Each entry owns a stable code ({@code ERR-JOURNEY-NOT-FOUND}), the HTTP status, and the message in English
 * and Arabic. The client shows the message in the reader's language and can branch on the code; the code never
 * changes once released, while the wording may.
 *
 * <p>Messages may contain {@code {0}}, {@code {1}} … placeholders filled from {@link ApiException} arguments. An
 * argument that has a different spelling per language is passed as {@link ApiException#text(String, String)}.
 *
 * <p>Add a new entry rather than reusing one with a different meaning, and never throw a bare
 * {@code ResponseStatusException} or an English string: the global handler turns anything that is not an
 * {@link ApiException} into {@link #INTERNAL}.
 */
public enum ErrorCode {

    // ─── General ────────────────────────────────────────────────────────────────────────
    INTERNAL("ERR-INTERNAL", HttpStatus.INTERNAL_SERVER_ERROR,
            "Something went wrong on our side. Please try again.",
            "حدث خطأ غير متوقع من جهتنا. يرجى المحاولة مرة أخرى."),
    ROUTE_NOT_FOUND("ERR-ROUTE-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This address does not exist.",
            "هذا العنوان غير موجود."),
    METHOD_NOT_ALLOWED("ERR-METHOD-NOT-ALLOWED", HttpStatus.METHOD_NOT_ALLOWED,
            "This action is not supported here.",
            "هذا الإجراء غير مدعوم هنا."),
    UNSUPPORTED_CONTENT_TYPE("ERR-UNSUPPORTED-CONTENT-TYPE", HttpStatus.UNSUPPORTED_MEDIA_TYPE,
            "The request was sent in a format this address does not accept.",
            "تم إرسال الطلب بصيغة لا يقبلها هذا العنوان."),
    MALFORMED_REQUEST("ERR-MALFORMED-REQUEST", HttpStatus.BAD_REQUEST,
            "The request could not be read. Check the data and try again.",
            "تعذّرت قراءة الطلب. تحقّق من البيانات وحاول مرة أخرى."),
    INVALID_PARAMETER("ERR-INVALID-PARAMETER", HttpStatus.BAD_REQUEST,
            "The value of \"{0}\" is not valid.",
            "قيمة \"{0}\" غير صالحة."),
    MISSING_PARAMETER("ERR-MISSING-PARAMETER", HttpStatus.BAD_REQUEST,
            "\"{0}\" is required.",
            "\"{0}\" مطلوب."),
    UNKNOWN_CODE("ERR-UNKNOWN-CODE", HttpStatus.BAD_REQUEST,
            "Unknown value: {0}.",
            "قيمة غير معروفة: {0}."),
    VALIDATION_FAILED("ERR-VALIDATION-FAILED", HttpStatus.BAD_REQUEST,
            "Some fields need attention.",
            "بعض الحقول تحتاج إلى مراجعة."),
    CONCURRENT_UPDATE("ERR-CONCURRENT-UPDATE", HttpStatus.CONFLICT,
            "Someone else changed this at the same time. Reload the page and try again.",
            "قام شخص آخر بتعديل هذا في نفس الوقت. أعد تحميل الصفحة وحاول مرة أخرى."),
    DATA_CONFLICT("ERR-DATA-CONFLICT", HttpStatus.CONFLICT,
            "This change conflicts with existing data. Reload the page and try again.",
            "يتعارض هذا التغيير مع بيانات موجودة. أعد تحميل الصفحة وحاول مرة أخرى."),

    // ─── Field validation (inside "fields" of ERR-VALIDATION-FAILED) ────────────────────
    FIELD_REQUIRED("ERR-FIELD-REQUIRED", HttpStatus.BAD_REQUEST,
            "This field is required.",
            "هذا الحقل مطلوب."),
    FIELD_LENGTH("ERR-FIELD-LENGTH", HttpStatus.BAD_REQUEST,
            "The length of this field is not allowed.",
            "طول هذا الحقل غير مسموح."),
    FIELD_EMAIL("ERR-FIELD-EMAIL", HttpStatus.BAD_REQUEST,
            "Enter a valid email address.",
            "أدخل بريدًا إلكترونيًا صحيحًا."),
    FIELD_RANGE("ERR-FIELD-RANGE", HttpStatus.BAD_REQUEST,
            "This value is out of the allowed range.",
            "هذه القيمة خارج النطاق المسموح."),
    FIELD_FORMAT("ERR-FIELD-FORMAT", HttpStatus.BAD_REQUEST,
            "This value has the wrong format.",
            "صيغة هذه القيمة غير صحيحة."),
    FIELD_INVALID("ERR-FIELD-INVALID", HttpStatus.BAD_REQUEST,
            "This value is not valid.",
            "هذه القيمة غير صالحة."),

    // ─── Sign-in and session ────────────────────────────────────────────────────────────
    AUTH_REQUIRED("ERR-AUTH-REQUIRED", HttpStatus.UNAUTHORIZED,
            "Please sign in to continue.",
            "يرجى تسجيل الدخول للمتابعة."),
    SESSION_EXPIRED("ERR-AUTH-SESSION-EXPIRED", HttpStatus.UNAUTHORIZED,
            "Your session has expired. Please sign in again.",
            "انتهت صلاحية جلستك. يرجى تسجيل الدخول مرة أخرى."),
    ACCOUNT_GONE("ERR-AUTH-ACCOUNT-GONE", HttpStatus.UNAUTHORIZED,
            "Your account no longer exists.",
            "حسابك لم يعد موجودًا."),
    INVALID_CREDENTIALS("ERR-AUTH-INVALID-CREDENTIALS", HttpStatus.UNAUTHORIZED,
            "Incorrect email or password.",
            "البريد الإلكتروني أو كلمة المرور غير صحيحة."),
    SIGNUP_DISABLED("ERR-AUTH-SIGNUP-DISABLED", HttpStatus.FORBIDDEN,
            "Self-service signup is disabled. Ask HR or your manager for an account.",
            "التسجيل الذاتي غير متاح. اطلب حسابًا من الموارد البشرية أو مديرك."),

    // ─── Access ─────────────────────────────────────────────────────────────────────────
    FORBIDDEN("ERR-ACCESS-FORBIDDEN", HttpStatus.FORBIDDEN,
            "You don't have permission to do this.",
            "ليست لديك صلاحية للقيام بذلك."),
    ROLE_NOT_ALLOWED("ERR-ACCESS-ROLE", HttpStatus.FORBIDDEN,
            "Your role cannot do this.",
            "دورك لا يسمح بالقيام بذلك."),
    PERSON_NOT_VISIBLE("ERR-ACCESS-PERSON", HttpStatus.FORBIDDEN,
            "You cannot view this person.",
            "لا يمكنك عرض بيانات هذا الشخص."),
    ACCOUNT_NOT_MANAGEABLE("ERR-ACCESS-ACCOUNT", HttpStatus.FORBIDDEN,
            "You cannot change this account.",
            "لا يمكنك تعديل هذا الحساب."),
    GRANT_ADMIN_ONLY("ERR-ACCESS-GRANT-ADMIN", HttpStatus.FORBIDDEN,
            "Only an Admin can grant the Admin role.",
            "لا يمنح دور مدير النظام إلا مدير النظام."),
    GRANT_ROLE_NOT_ALLOWED("ERR-ACCESS-GRANT-ROLE", HttpStatus.FORBIDDEN,
            "A Manager cannot grant the {0} role.",
            "لا يمكن للمدير منح دور {0}."),
    OWN_DEPARTMENT_ONLY("ERR-ACCESS-OWN-DEPARTMENT", HttpStatus.FORBIDDEN,
            "A Manager can only work within their own department.",
            "يمكن للمدير العمل ضمن إدارته فقط."),
    NO_ORGANISATION_VIEW("ERR-ACCESS-ORG-VIEW", HttpStatus.FORBIDDEN,
            "Your role has no organisation-wide view.",
            "دورك لا يتيح عرضًا على مستوى المنظمة."),
    OWN_LEARNERS_ONLY("ERR-ACCESS-OWN-LEARNERS", HttpStatus.FORBIDDEN,
            "A Senior can only see their own learners.",
            "يمكن للمشرف رؤية المتعلمين التابعين له فقط."),
    REVIEWER_ONLY("ERR-ACCESS-REVIEWER-ONLY", HttpStatus.FORBIDDEN,
            "Only the learner's reviewer can do this.",
            "لا يمكن القيام بذلك إلا من قِبل مراجع المتعلم."),
    LEARNER_ONLY("ERR-ACCESS-LEARNER-ONLY", HttpStatus.FORBIDDEN,
            "Only the learner can do this.",
            "لا يمكن القيام بذلك إلا من قِبل المتعلم نفسه."),

    // ─── People ─────────────────────────────────────────────────────────────────────────
    USER_NOT_FOUND("ERR-USER-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This person could not be found.",
            "تعذّر العثور على هذا الشخص."),
    EMAIL_TAKEN("ERR-USER-EMAIL-TAKEN", HttpStatus.CONFLICT,
            "An account with this email already exists.",
            "يوجد حساب بهذا البريد الإلكتروني بالفعل."),
    USER_HAS_LEARNERS("ERR-USER-HAS-LEARNERS", HttpStatus.CONFLICT,
            "{0} still has {1} learner(s). Reassign them first.",
            "لا يزال لدى {0} عدد {1} من المتعلمين. أعد تعيينهم أولًا."),
    DELETE_OWN_ACCOUNT("ERR-USER-DELETE-SELF", HttpStatus.CONFLICT,
            "You cannot delete your own account.",
            "لا يمكنك حذف حسابك الخاص."),
    NOT_A_SENIOR("ERR-USER-NOT-SENIOR", HttpStatus.BAD_REQUEST,
            "{0} is not a Senior.",
            "{0} ليس مشرفًا."),
    NOT_A_LEARNER("ERR-USER-NOT-LEARNER", HttpStatus.BAD_REQUEST,
            "{0} is not a Learner.",
            "{0} ليس متعلمًا."),
    UNKNOWN_SENIOR("ERR-USER-UNKNOWN-SENIOR", HttpStatus.BAD_REQUEST,
            "The selected senior does not exist.",
            "المشرف المحدد غير موجود."),
    SENIOR_OTHER_DEPARTMENT("ERR-USER-SENIOR-OTHER-DEPARTMENT", HttpStatus.BAD_REQUEST,
            "{0} is in a different department.",
            "{0} في إدارة مختلفة."),
    UNSUPPORTED_LANGUAGE("ERR-USER-LANGUAGE", HttpStatus.BAD_REQUEST,
            "Unsupported language. Use English or Arabic.",
            "لغة غير مدعومة. استخدم العربية أو الإنجليزية."),
    NO_REVIEWER("ERR-USER-NO-REVIEWER", HttpStatus.CONFLICT,
            "You don't have a senior or a manager yet, so nobody could review your work. Ask HR to set one.",
            "ليس لديك مشرف أو مدير بعد، لذلك لا يوجد من يراجع عملك. اطلب من الموارد البشرية تعيين أحدهم."),

    // ─── Departments ────────────────────────────────────────────────────────────────────
    DEPARTMENT_NOT_FOUND("ERR-DEPARTMENT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This department could not be found.",
            "تعذّر العثور على هذه الإدارة."),
    UNKNOWN_DEPARTMENT("ERR-DEPARTMENT-UNKNOWN", HttpStatus.BAD_REQUEST,
            "The selected department does not exist.",
            "الإدارة المحددة غير موجودة."),
    DEPARTMENT_NAME_TAKEN("ERR-DEPARTMENT-NAME-TAKEN", HttpStatus.CONFLICT,
            "A department with that name already exists.",
            "توجد إدارة بهذا الاسم بالفعل."),
    DEPARTMENT_HAS_MEMBERS("ERR-DEPARTMENT-HAS-MEMBERS", HttpStatus.CONFLICT,
            "This department still has {0} member(s). Move them to another department first.",
            "لا تزال هذه الإدارة تضم {0} من الأعضاء. انقلهم إلى إدارة أخرى أولًا."),

    // ─── Journeys ───────────────────────────────────────────────────────────────────────
    JOURNEY_NOT_FOUND("ERR-JOURNEY-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This journey could not be found.",
            "تعذّر العثور على هذا المسار."),
    JOURNEY_NEEDS_ITEM("ERR-JOURNEY-NEEDS-ITEM", HttpStatus.BAD_REQUEST,
            "A journey needs at least one item.",
            "يحتاج المسار إلى عنصر واحد على الأقل."),
    UNIT_NEEDS_ITEM("ERR-JOURNEY-UNIT-NEEDS-ITEM", HttpStatus.BAD_REQUEST,
            "Unit \"{0}\" needs at least one item.",
            "الوحدة \"{0}\" تحتاج إلى عنصر واحد على الأقل."),
    QUIZ_TOO_MANY_QUESTIONS("ERR-QUIZ-TOO-MANY-QUESTIONS", HttpStatus.BAD_REQUEST,
            "A unit quiz can have at most {0} questions.",
            "يمكن أن يحتوي اختبار الوحدة على {0} أسئلة كحد أقصى."),
    QUIZ_OPEN_QUESTION("ERR-QUIZ-OPEN-QUESTION", HttpStatus.BAD_REQUEST,
            "Unit quizzes grade themselves, so they take multiple-choice or yes/no questions only.",
            "تُصحَّح اختبارات الوحدات تلقائيًا، لذا تقبل أسئلة الاختيار من متعدد أو نعم/لا فقط."),
    QUESTION_PROMPT_REQUIRED("ERR-QUIZ-PROMPT-REQUIRED", HttpStatus.BAD_REQUEST,
            "Every question needs a prompt.",
            "يحتاج كل سؤال إلى نص."),
    QUESTION_OPTION_COUNT("ERR-QUIZ-OPTION-COUNT", HttpStatus.BAD_REQUEST,
            "A multiple-choice question needs 2 to 4 options.",
            "يحتاج سؤال الاختيار من متعدد إلى خيارين إلى أربعة خيارات."),
    QUESTION_CORRECT_OPTION("ERR-QUIZ-CORRECT-OPTION", HttpStatus.BAD_REQUEST,
            "Pick the correct option for \"{0}\".",
            "اختر الإجابة الصحيحة للسؤال \"{0}\"."),
    QUESTION_CORRECT_YES_NO("ERR-QUIZ-CORRECT-YES-NO", HttpStatus.BAD_REQUEST,
            "Pick yes or no as the answer for \"{0}\".",
            "اختر نعم أو لا كإجابة للسؤال \"{0}\"."),
    ATTACHMENT_FILE_REQUIRED("ERR-ATTACHMENT-FILE-REQUIRED", HttpStatus.BAD_REQUEST,
            "{0} attachments need an uploaded file.",
            "مرفقات {0} تحتاج إلى ملف مرفوع."),
    ATTACHMENT_URL_INVALID("ERR-ATTACHMENT-URL-INVALID", HttpStatus.BAD_REQUEST,
            "{0} attachments need an http or https URL.",
            "مرفقات {0} تحتاج إلى رابط يبدأ بـ http أو https."),

    // ─── Packages ───────────────────────────────────────────────────────────────────────
    PACKAGE_NOT_FOUND("ERR-PACKAGE-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This package could not be found.",
            "تعذّر العثور على هذه الحزمة."),
    PACKAGE_IN_USE("ERR-PACKAGE-IN-USE", HttpStatus.CONFLICT,
            "This package has been assigned, so it can't be deleted.",
            "تم تعيين هذه الحزمة، لذا لا يمكن حذفها."),
    PACKAGE_DUPLICATE_JOURNEY("ERR-PACKAGE-DUPLICATE-JOURNEY", HttpStatus.BAD_REQUEST,
            "A journey can only appear once in a package.",
            "لا يمكن أن يظهر المسار أكثر من مرة في الحزمة."),
    PACKAGE_EMPTY("ERR-PACKAGE-EMPTY", HttpStatus.BAD_REQUEST,
            "This package has no journeys.",
            "لا تحتوي هذه الحزمة على أي مسارات."),
    PACKAGE_ALREADY_ASSIGNED("ERR-PACKAGE-ALREADY-ASSIGNED", HttpStatus.CONFLICT,
            "This learner already has that package.",
            "هذا المتعلم لديه هذه الحزمة بالفعل."),
    PACKAGE_ASSIGNMENT_NOT_FOUND("ERR-PACKAGE-ASSIGNMENT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This package assignment could not be found.",
            "تعذّر العثور على تعيين الحزمة هذا."),
    PACKAGE_ALREADY_ENROLLED("ERR-PACKAGE-ALREADY-ENROLLED", HttpStatus.CONFLICT,
            "You are already enrolled in this package.",
            "أنت مسجّل في هذه الحزمة بالفعل."),

    // ─── Assignments and progress ───────────────────────────────────────────────────────
    ASSIGNMENT_NOT_FOUND("ERR-ASSIGNMENT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This assigned journey could not be found.",
            "تعذّر العثور على هذا المسار المعيّن."),
    ALREADY_ASSIGNED("ERR-ASSIGNMENT-DUPLICATE", HttpStatus.CONFLICT,
            "This learner is already assigned to that journey.",
            "هذا المتعلم معيّن لهذا المسار بالفعل."),
    ALREADY_ENROLLED("ERR-ASSIGNMENT-ALREADY-ENROLLED", HttpStatus.CONFLICT,
            "You are already enrolled in this journey.",
            "أنت مسجّل في هذا المسار بالفعل."),
    DUE_DATE_IN_PAST("ERR-ASSIGNMENT-DUE-DATE-PAST", HttpStatus.BAD_REQUEST,
            "The due date can't be in the past.",
            "لا يمكن أن يكون تاريخ الاستحقاق في الماضي."),
    PROGRESS_NOT_ALLOWED("ERR-ASSIGNMENT-PROGRESS-FORBIDDEN", HttpStatus.FORBIDDEN,
            "You cannot change this learner's progress.",
            "لا يمكنك تغيير تقدم هذا المتعلم."),
    TIME_SPENT_REQUIRED("ERR-ASSIGNMENT-TIME-REQUIRED", HttpStatus.BAD_REQUEST,
            "Enter the time spent when marking an item completed.",
            "أدخل الوقت المستغرق عند تحديد العنصر كمكتمل."),
    ITEM_PROGRESS_NOT_FOUND("ERR-ASSIGNMENT-ITEM-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This item could not be found.",
            "تعذّر العثور على هذا العنصر."),
    JOURNEY_CANCELLED("ERR-ASSIGNMENT-CANCELLED", HttpStatus.CONFLICT,
            "This journey was cancelled.",
            "تم إلغاء هذا المسار."),

    // ─── Units ──────────────────────────────────────────────────────────────────────────
    UNIT_PROGRESS_NOT_FOUND("ERR-UNIT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This unit could not be found.",
            "تعذّر العثور على هذه الوحدة."),
    UNIT_CLOSED("ERR-UNIT-CLOSED", HttpStatus.CONFLICT,
            "This unit is closed.",
            "هذه الوحدة مغلقة."),
    UNIT_NO_QUIZ("ERR-UNIT-NO-QUIZ", HttpStatus.NOT_FOUND,
            "This unit has no quiz.",
            "لا يوجد اختبار لهذه الوحدة."),
    QUIZ_ANSWER_ALL("ERR-UNIT-QUIZ-ANSWER-ALL", HttpStatus.BAD_REQUEST,
            "Answer every question before submitting.",
            "أجب عن جميع الأسئلة قبل الإرسال."),
    UNIT_NOT_READY("ERR-UNIT-NOT-READY", HttpStatus.CONFLICT,
            "Finish every item and the quiz first.",
            "أكمل جميع العناصر والاختبار أولًا."),
    UNIT_ALREADY_SUBMITTED("ERR-UNIT-ALREADY-SUBMITTED", HttpStatus.CONFLICT,
            "This unit is already with your reviewer or closed.",
            "هذه الوحدة لدى المراجع بالفعل أو مغلقة."),

    // ─── Exams ──────────────────────────────────────────────────────────────────────────
    EXAM_NOT_FOUND("ERR-EXAM-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This exam could not be found.",
            "تعذّر العثور على هذا الاختبار."),
    EXAM_ALREADY_SUBMITTED("ERR-EXAM-ALREADY-SUBMITTED", HttpStatus.CONFLICT,
            "This exam has already been submitted.",
            "تم إرسال هذا الاختبار بالفعل."),
    EXAM_UNKNOWN_QUESTION("ERR-EXAM-UNKNOWN-QUESTION", HttpStatus.BAD_REQUEST,
            "An answer refers to a question that is not on this exam.",
            "تشير إحدى الإجابات إلى سؤال غير موجود في هذا الاختبار."),
    EXAM_ATTEMPT_NOT_FOUND("ERR-EXAM-ATTEMPT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This exam attempt could not be found.",
            "تعذّر العثور على محاولة الاختبار هذه."),
    EXAM_GRADE_NOT_ALLOWED("ERR-EXAM-GRADE-FORBIDDEN", HttpStatus.FORBIDDEN,
            "You cannot grade this exam.",
            "لا يمكنك تصحيح هذا الاختبار."),
    EXAM_NOTHING_TO_GRADE("ERR-EXAM-NOTHING-TO-GRADE", HttpStatus.BAD_REQUEST,
            "This attempt has no answers to grade.",
            "لا تحتوي هذه المحاولة على إجابات للتصحيح."),
    EXAM_NEEDS_QUESTION("ERR-EXAM-NEEDS-QUESTION", HttpStatus.BAD_REQUEST,
            "An exam needs at least one question.",
            "يحتاج الاختبار إلى سؤال واحد على الأقل."),
    EXAM_LOCKED("ERR-EXAM-LOCKED", HttpStatus.CONFLICT,
            "The final exam opens once every unit's items and quiz are done.",
            "يُفتح الاختبار النهائي بعد إكمال عناصر جميع الوحدات واختباراتها."),
    EXAM_ANSWER_ALL("ERR-EXAM-ANSWER-ALL", HttpStatus.BAD_REQUEST,
            "Answer every question once before submitting.",
            "أجب عن كل سؤال مرة واحدة قبل الإرسال."),
    EXAM_RESULT_REQUIRED("ERR-EXAM-RESULT-REQUIRED", HttpStatus.BAD_REQUEST,
            "Choose whether the learner passed or failed.",
            "حدّد ما إذا كان المتعلم ناجحًا أم راسبًا."),
    EXAM_OPTION_OUT_OF_RANGE("ERR-EXAM-OPTION-OUT-OF-RANGE", HttpStatus.BAD_REQUEST,
            "An answer option is out of range.",
            "أحد خيارات الإجابة خارج النطاق."),

    // ─── Files ──────────────────────────────────────────────────────────────────────────
    FILE_REQUIRED("ERR-FILE-REQUIRED", HttpStatus.BAD_REQUEST,
            "No file was supplied.",
            "لم يتم إرفاق أي ملف."),
    FILE_TOO_LARGE("ERR-FILE-TOO-LARGE", HttpStatus.PAYLOAD_TOO_LARGE,
            "The file is larger than the {0} MB limit.",
            "حجم الملف أكبر من الحد المسموح ({0} ميجابايت)."),
    FILE_TYPE_NOT_ALLOWED("ERR-FILE-TYPE", HttpStatus.BAD_REQUEST,
            "This file type is not supported ({0}).",
            "نوع الملف غير مدعوم ({0})."),
    FILE_STORE_FAILED("ERR-FILE-STORE-FAILED", HttpStatus.INTERNAL_SERVER_ERROR,
            "The file could not be saved. Please try again.",
            "تعذّر حفظ الملف. يرجى المحاولة مرة أخرى."),
    FILE_NOT_FOUND("ERR-FILE-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This file could not be found.",
            "تعذّر العثور على هذا الملف."),
    FILE_KEY_INVALID("ERR-FILE-KEY-INVALID", HttpStatus.BAD_REQUEST,
            "The file reference is not valid.",
            "مرجع الملف غير صالح."),
    FILE_RANGE_INVALID("ERR-FILE-RANGE-INVALID", HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE,
            "The requested part of the file is not available.",
            "الجزء المطلوب من الملف غير متاح."),

    // ─── Announcements ──────────────────────────────────────────────────────────────────
    ANNOUNCEMENT_NOT_FOUND("ERR-ANNOUNCEMENT-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This announcement could not be found.",
            "تعذّر العثور على هذا الإعلان."),
    ANNOUNCEMENT_NOT_ADDRESSED("ERR-ANNOUNCEMENT-NOT-ADDRESSED", HttpStatus.FORBIDDEN,
            "This announcement is not addressed to you.",
            "هذا الإعلان غير موجّه إليك."),
    ANNOUNCEMENT_OWN_ONLY("ERR-ANNOUNCEMENT-OWN-ONLY", HttpStatus.FORBIDDEN,
            "You can only change announcements you posted.",
            "يمكنك تعديل الإعلانات التي نشرتها فقط."),
    ANNOUNCEMENT_TITLE_REQUIRED("ERR-ANNOUNCEMENT-TITLE-REQUIRED", HttpStatus.BAD_REQUEST,
            "Give the announcement a title.",
            "أضف عنوانًا للإعلان."),
    ANNOUNCEMENT_BODY_REQUIRED("ERR-ANNOUNCEMENT-BODY-REQUIRED", HttpStatus.BAD_REQUEST,
            "Write the announcement.",
            "اكتب نص الإعلان."),
    ANNOUNCEMENT_SHOW_UNTIL_PAST("ERR-ANNOUNCEMENT-SHOW-UNTIL-PAST", HttpStatus.BAD_REQUEST,
            "The show-until date is in the past.",
            "تاريخ انتهاء العرض في الماضي."),
    ANNOUNCEMENT_SHOW_UNTIL_TOO_FAR("ERR-ANNOUNCEMENT-SHOW-UNTIL-TOO-FAR", HttpStatus.BAD_REQUEST,
            "An announcement can show for at most a year.",
            "يمكن عرض الإعلان لمدة سنة كحد أقصى."),
    ANNOUNCEMENT_AUDIENCE_REQUIRED("ERR-ANNOUNCEMENT-AUDIENCE-REQUIRED", HttpStatus.BAD_REQUEST,
            "Choose who the announcement is for.",
            "اختر الفئة الموجّه إليها الإعلان."),

    // ─── Certificates ───────────────────────────────────────────────────────────────────
    CERTIFICATE_NOT_FOUND("ERR-CERTIFICATE-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This certificate could not be found.",
            "تعذّر العثور على هذه الشهادة."),

    // ─── Notifications and email ────────────────────────────────────────────────────────
    NOTIFICATION_NOT_FOUND("ERR-NOTIFICATION-NOT-FOUND", HttpStatus.NOT_FOUND,
            "This notification could not be found.",
            "تعذّر العثور على هذا الإشعار."),
    MAIL_DISABLED("ERR-MAIL-DISABLED", HttpStatus.CONFLICT,
            "Email is turned off. Set MAIL_ENABLED=true (app.notifications.mail.enabled) and restart.",
            "البريد الإلكتروني متوقف. اضبط MAIL_ENABLED=true ثم أعد التشغيل."),
    MAIL_NOT_CONFIGURED("ERR-MAIL-NOT-CONFIGURED", HttpStatus.CONFLICT,
            "No mail server is configured. Set SMTP_HOST (app.mail.host) and restart.",
            "لم يتم إعداد خادم البريد. اضبط SMTP_HOST ثم أعد التشغيل."),
    MAIL_NO_ADDRESS("ERR-MAIL-NO-ADDRESS", HttpStatus.CONFLICT,
            "Your account has no email address.",
            "لا يوجد بريد إلكتروني مرتبط بحسابك."),
    MAIL_REJECTED("ERR-MAIL-REJECTED", HttpStatus.CONFLICT,
            "The mail server did not accept the message: {0}",
            "لم يقبل خادم البريد الرسالة: {0}");

    private final String code;
    private final HttpStatus status;
    private final String english;
    private final String arabic;

    ErrorCode(String code, HttpStatus status, String english, String arabic) {
        this.code = code;
        this.status = status;
        this.english = english;
        this.arabic = arabic;
    }

    public String getCode() { return code; }
    public HttpStatus getStatus() { return status; }
    public String getEnglish() { return english; }
    public String getArabic() { return arabic; }
}
